# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_lesson_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
