# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20171013_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='studentExperience',
            new_name='student_experience',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tutorial_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='tutorials.TutorialSeries'),
        ),
    ]
